version: '1.0'
services:
  postgres:
    container_name: user_crud_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: "user_crud_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5495:5432"
    networks:
      - user_crud_network
  php-fpm:
    container_name: user_crud_php
    build:
      context: .
      dockerfile: docker/Dockerfile-php-fpm
    volumes:
      - ./:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm.www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file:
      - .env
    networks:
      - user_crud_network
  nginx:
    container_name: user_crud_nginx
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9999:9999"
    networks:
      - user_crud_network

networks:
  user_crud_network:
