controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_get:
    path: /user/{id}
    controller: App\Controller\UserCrudController::getById
    methods: GET

user_create:
    path: /user
    controller: App\Controller\UserCrudController::create
    methods: POST

user_update:
    path: /user/{id}
    controller: App\Controller\UserCrudController::update
    methods: PUT

user_delete:
    path: /user/{id}
    controller: App\Controller\UserCrudController::delete
    methods: DELETE
